server:
    num-threads: 2
    msg-cache-size: 256m
    rrset-cache-size: 512m
    msg-cache-slabs: 4
    rrset-cache-slabs: 4
    infra-cache-slabs: 4
    key-cache-slabs: 4
    so-rcvbuf: 4m
    so-sndbuf: 4m
    so-reuseport: yes
    cache-min-ttl: 3600
    cache-max-ttl: 7776000
    cache-max-negative-ttl: 3600
    prefetch: yes
    prefetch-key: yes
    serve-expired: yes
    serve-expired-ttl: 7776000
    minimal-responses: yes
    qname-minimisation: yes
