[Interface]
# Fill in with the private key generated on the server:
#   sudo cat /tmp/laptop-private.key
PrivateKey = eA/vke6NAjAl6zsOE/9Ln9/TWfmF3O2DT3tIKmm2t28=
Address    = 10.8.0.5/32
DNS        = 10.8.0.1

[Peer]
PublicKey           = Pa6JyzcTtxtoyz0f7n9X7dBdOmS1AII9vIaCTEZdhwU=
Endpoint            = 47.14.39.51:51820
AllowedIPs          = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
